/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-01-02

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include <stdio.h>
#include"ADC.h"
#include"DAC.h"
#include"USART.h"
#include "PulseOximeter.h"

/* Private macro */
/* Private variables */
float ir_baseline = 0;
float red_baseline = 0;
float ir_value = 0;
float red_value = 0;

unsigned char Updateflag = 0;

char buffer[20];
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	unsigned long i = 0;

  /* Initialize system */
  SystemInit();

  InitUSART();
  InitDAC();
  InitADS1115();
  SPO2ResetVariables();

  GPIO_InitTypeDef GPIO_InitStructure;
  RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);

  /*enable LED on disco*/
  GPIO_InitStructure.GPIO_Pin = GPIO_Pin_15;
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
  GPIO_Init(GPIOD, &GPIO_InitStructure);

  TIM_TimeBaseInitTypeDef TIM_TimeBaseStruct;
  NVIC_InitTypeDef  NVIC_InitStruct;

  /*Clock source for TIM1 and TIM8*/
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_TIM1, ENABLE);

  /*Timer to reset the cranking*/
  TIM_TimeBaseStructInit(&TIM_TimeBaseStruct);
  TIM_TimeBaseStruct.TIM_Period = 420-1; // 100kHz
  TIM_TimeBaseStruct.TIM_Prescaler = 0; // 42MHz
  TIM_TimeBaseStruct.TIM_ClockDivision = TIM_CKD_DIV1;
  TIM_TimeBaseStruct.TIM_CounterMode = TIM_CounterMode_Up;
  TIM_TimeBaseStruct.TIM_RepetitionCounter = 0;
  TIM_TimeBaseInit(TIM1, &TIM_TimeBaseStruct);

  /* Clear update interrupt bit*/
  TIM_ClearITPendingBit(TIM1, TIM1_UP_TIM10_IRQn);

  /*Enable Timer Interrupt*/
  TIM_ITConfig(TIM1, TIM_IT_Update, ENABLE);

  /* TIM1 counter disable */
  TIM_Cmd(TIM1, ENABLE);

  /*Enable TIM1 IRQ*/
  NVIC_InitStruct.NVIC_IRQChannel = TIM1_UP_TIM10_IRQn;
  NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 4;
  NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
  NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
  NVIC_Init(&NVIC_InitStruct);

  printf("Value baseline IR, Value IR, Value baseline Red, Value Red\n\r");
  printf("ADC step size is 125uV\n\r");


  /* Infinite loop */
  while (1)
  {
	  if(Updateflag == 1){
		  SPO2Measuring();
		  Updateflag = 0;
	  }
  }
}

void TIM1_UP_TIM10_IRQHandler(void){

	if(TIM_GetITStatus(TIM1,TIM_IT_Update)){

		ElapsedTimeIn_us++;
		Updateflag = 1;
	}
	TIM_ClearFlag(TIM1,TIM_FLAG_Update);
}
